default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  # NOTE: This hook formats the tables in markdown files ensuring consistent formatting
  - repo: local
    hooks:
      - id: markdown-table-format
        name: markdown-table-format
        language: node
        additional_dependencies:
          - markdown-table-formatter
        pass_filenames: false
        entry: bash -c "markdown-table-formatter"

  # NOTE: This hook lints commit messages within a specified range, ideal for validating all commits in a PR.
  # Environment variables $FROM (start of range) and $TO (end of range) are set in PR Checks workflow.
  - repo: local
    hooks:
      - id: pr-commit-lint
        name: pr-commit-lint
        stages: [manual]
        language: node
        additional_dependencies:
          - "@commitlint/cli"
          - "@commitlint/config-conventional"
        pass_filenames: false
        entry: bash -c "commitlint --from $FROM --to $TO --verbose"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.0
    hooks:
      - id: yamllint

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [--ignore-words=.codespellignore]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.22.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
